# Generated by Django 4.2.3 on 2023-07-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('userId', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tital', models.CharField(max_length=255)),
                ('completed', models.CharField(max_length=255)),
            ],
        ),
    ]
