# Generated by Django 4.2.3 on 2023-08-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tital',
            new_name='title',
        ),
    ]
